### ISSUE TITLE
0.1.0 release checklist

### ISSUE THREAD

**Issue by sandhose** [matrix-org/rust-opa-wasm#6]
I'd like to release a 0.1.0 version on crates.io. Here's a rough checklist of things which needs to happen first:

 - [x] #5 
 - [ ] #2 
 - [x] Setup Dependabot
 - [x] Meaningful docs (with the right attributes on docs.rs to document the features (like [this](https://github.com/rust-embedded/gpio-cdev/blob/master/src/lib.rs#L120))
 - [x] Raise the clippy lints and resolve them
 - [x] Have a good test coverage (probably mainly through integration tests)
 - [ ] More builtins (#1)
 - [x] A bundle loader (#8)

**Comment by NewbMiao** [comment]
Hi, when will we release it on crates.io? Keen to have a play it then

**Comment by immesys** [comment]
Hey there. Please publish a version on crates.io. I have a library I'd like to publish that uses this, but you cannot publish something to crates.io with a git dependency

**Comment by sandhose** [comment]
I have great news for y'all: I just published version 0.1.0 on crates.io!

The release workflow is setup, so releasing new versions should be streamlined enough for next time :)
